### ISSUE TITLE
PhysUtil Times Out on trinket.io

### ISSUE THREAD

**Issue by lernerphysics** [perlatmsu/physutil#15]
Every time I try to load PhysUtil on Trinket's GlowScript implementation, it times out.

https://trinket.io/glowscript/9e0ae56f0c

Is it because Trinket has GlowScript version 2.3 as its newest implementation? Is it because I have the wrong address?

**Comment by dannycab** [comment]
Please use PhysUtil located here: https://github.com/PERLMSU/physutil

And change the get_library call to point here: https://raw.githubusercontent.com/PERLMSU/physutil/master/js/physutil.js

**Comment by brianpmarks** [comment]
@dannycab FYI, when using the `raw.githubusercontent.com` host, I see errors in Chrome's dev tools saying it's refusing to execute the script because it's MIME type (text/plain) is not executable.

From this [SO article](http://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github) I got the hint to use `rawgit.com` instead and that is working for me. In this case the URL for the `get_library` call would be:

https://cdn.rawgit.com/PERLMSU/physutil/master/js/physutil.js

Here is a working copy of @lernerphysics's example on Trinket:

https://trinket.io/embed/glowscript/88929a356f

**Comment by dannycab** [comment]
Thanks @brianpmarks. I've updated the installation page here: https://perlmsu.github.io/physutil/installation/
